### ISSUE TITLE
"labelledBy" prop does not change the placeholder

### ISSUE THREAD

**Issue by usaidsherwani** [hc-oss/react-multi-select-component#591] opened 2022-05-24 10:32 UTC
Hi, I am using react-multi-select-component 4.2.4 and I am facing an issue that when I try to change the placeholder by given prop "labelledBy" it does not change the output. It always shows the default placeholder which is "select...".

When I inspect on browser I saw there is a `<span class="gray">Select...</span>` which always trigger and ignore whatever value I set in prop "labelledBy". I have attached a screenshot as well in which my "aria-labelledBy" value is "select badgeeeee".

![dropdown](https://user-images.githubusercontent.com/28630511/170011906-2d7feb67-f837-4882-8c4d-1ca802a1fdb5.png)

**Comment by SherothKar** [comment] 2022-05-24 11:09
I'm also facing the same issue. Let me know once it's fixed.

**Comment by harshzalavadiya** [comment] 2022-05-24 11:23
Duplicate of #429

@usaidsherwani @SherothKar please see below answer

https://github.com/hc-oss/react-multi-select-component/issues/429#issuecomment-885676412

**Closed by harshzalavadiya** 2022-05-24 11:23 UTC
Labels: bug

**Comment by usaidsherwani** [comment] 2022-05-24 11:59
> Duplicate of #429
> 
> @usaidsherwani @SherothKar please see below answer
> 
> [#429 (comment)](https://github.com/hc-oss/react-multi-select-component/issues/429#issuecomment-885676412)

Oh! thank you so much. It solved the problem :D :D

**Comment by SherothKar** [comment] 2022-05-24 12:09
Thank You! ✌️
